<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Update error &quot;failed to return clean data&quot;</title>
    <link>http://forums.whonix.org/t/update-error-failed-to-return-clean-data/12406</link>
    <description>Whenever I try to update Whonix via the qubes updater, I get an error (below). I&#39;ve been getting this error since I installed qubes about a week ago, and I haven&#39;t had a problem on any other qube so I assume it&#39;s a Whonix issue. Running &quot;sudo apt-get update&quot; then &quot;sudo apt-get upgrade&quot; works fine in a standalone VM based on whonix, but it also gives the same error using the qubes updater gui tool.

I&#39;m using whonix workstation 16.

Here&#39;s the error copied from the updater tool:
    Updating whonix-ws-16

    Error on updating whonix-ws-16: Command &#39;[&#39;sudo&#39;, &#39;qubesctl&#39;, &#39;--skip-dom0&#39;, &#39;--targets=whonix-ws-16&#39;, &#39;--show-output&#39;, &#39;state.sls&#39;, &#39;update.qubes-vm&#39;]&#39; returned non-zero exit status 20
    whonix-ws-16:
          ----------
          _error:
              Failed to return clean data
          retcode:
              1
          stderr:
              Traceback (most recent call last):
                File &quot;/var/tmp/.root_dd8a91_salt/salt-call&quot;, line 27, in &lt;module&gt;
                  salt_call()
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/scripts.py&quot;, line 445, in salt_call
                  client.run()
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/cli/call.py&quot;, line 48, in run
                  caller = salt.cli.caller.Caller.factory(self.config)
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py&quot;, line 64, in factory
                  return ZeroMQCaller(opts, **kwargs)
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py&quot;, line 329, in __init__
                  super(ZeroMQCaller, self).__init__(opts)
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py&quot;, line 89, in __init__
                  self.minion = salt.minion.SMinion(opts)
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/minion.py&quot;, line 912, in __init__
                  opts[&quot;grains&quot;] = salt.loader.grains(opts)
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/loader.py&quot;, line 825, in grains
                  ret = funcs[key]()
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/grains/core.py&quot;, line 2384, in ip_fqdn
                  ret[&quot;ipv6&quot;] = salt.utils.network.ip_addrs6(include_loopback=True)
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/utils/network.py&quot;, line 1353, in ip_addrs6
                  return _ip_addrs(interface, include_loopback, interface_data, &quot;inet6&quot;)
                File &quot;/var/tmp/.root_dd8a91_salt/pyall/salt/utils/network.py&quot;, line 1333, in _ip_addrs
                  ret.add(addr)
                File &quot;/usr/lib/python3.9/ipaddress.py&quot;, line 1920, in __hash__
                  return hash((self._ip, self._scope_id))
              AttributeError: _scope_id
          stdout:</description>
    <language>en</language>
    <lastBuildDate>Tue, 21 Sep 2021 08:04:28 +0000</lastBuildDate>
    <category>Qubes-Whonix</category>
    <atom:link href="http://forums.whonix.org/t/update-error-failed-to-return-clean-data/12406.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Update error &quot;failed to return clean data&quot;</title>
        <dc:creator><![CDATA[Patrick]]></dc:creator>
        <description><![CDATA[
            <p>Whonix doesn’t develop salt. That’s part of Qubes.<br>
Therefore could you please report this at <a href="https://github.com/QubesOS/qubes-issues/issues">https://github.com/QubesOS/qubes-issues/issues</a>?</p>
          <p><a href="http://forums.whonix.org/t/update-error-failed-to-return-clean-data/12406/2">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/update-error-failed-to-return-clean-data/12406/2</link>
        <pubDate>Tue, 21 Sep 2021 08:04:28 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-12406-2</guid>
        <source url="http://forums.whonix.org/t/update-error-failed-to-return-clean-data/12406.rss">Update error &quot;failed to return clean data&quot;</source>
      </item>
      <item>
        <title>Update error &quot;failed to return clean data&quot;</title>
        <dc:creator><![CDATA[boogabooga]]></dc:creator>
        <description><![CDATA[
            <p>Whenever I try to update Whonix via the qubes updater, I get an error (below). I’ve been getting this error since I installed qubes about a week ago, and I haven’t had a problem on any other qube so I assume it’s a Whonix issue. Running “sudo apt-get update” then “sudo apt-get upgrade” works fine in a standalone VM based on whonix, but it also gives the same error using the qubes updater gui tool.</p>
<p>I’m using whonix workstation 16.</p>
<p>Here’s the error copied from the updater tool:<br>
Updating whonix-ws-16</p>
<pre><code>Error on updating whonix-ws-16: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=whonix-ws-16', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20
whonix-ws-16:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/var/tmp/.root_dd8a91_salt/salt-call", line 27, in &lt;module&gt;
              salt_call()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/scripts.py", line 445, in salt_call
              client.run()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/call.py", line 48, in run
              caller = salt.cli.caller.Caller.factory(self.config)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 64, in factory
              return ZeroMQCaller(opts, **kwargs)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 329, in __init__
              super(ZeroMQCaller, self).__init__(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 89, in __init__
              self.minion = salt.minion.SMinion(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/minion.py", line 912, in __init__
              opts["grains"] = salt.loader.grains(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader.py", line 825, in grains
              ret = funcs[key]()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/grains/core.py", line 2384, in ip_fqdn
              ret["ipv6"] = salt.utils.network.ip_addrs6(include_loopback=True)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/network.py", line 1353, in ip_addrs6
              return _ip_addrs(interface, include_loopback, interface_data, "inet6")
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/network.py", line 1333, in _ip_addrs
              ret.add(addr)
            File "/usr/lib/python3.9/ipaddress.py", line 1920, in __hash__
              return hash((self._ip, self._scope_id))
          AttributeError: _scope_id
      stdout:</code></pre>
          <p><a href="http://forums.whonix.org/t/update-error-failed-to-return-clean-data/12406/1">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/update-error-failed-to-return-clean-data/12406/1</link>
        <pubDate>Mon, 20 Sep 2021 19:49:18 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-12406-1</guid>
        <source url="http://forums.whonix.org/t/update-error-failed-to-return-clean-data/12406.rss">Update error &quot;failed to return clean data&quot;</source>
      </item>
  </channel>
</rss>
