<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Live Snapshots don&#39;t work</title>
    <link>http://forums.whonix.org/t/live-snapshots-dont-work/8606</link>
    <description>KVM, Whonix-15.0.0.7.1: Live snapshots don&#39;t work

When I want to start a saved live snapshot I always get error messages like this:


internal error: process exited while connecting to monitor: 2019-12-08T08:01:21.847930Z qemu-system-x86_64: Device &#39;drive-virtio-disk0&#39; does not have the requested snapshot &#39;snapshot1&#39;

Traceback (most recent call last):
  File &quot;/usr/share/virt-manager/virtManager/asyncjob.py&quot;, line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File &quot;/usr/share/virt-manager/virtManager/asyncjob.py&quot;, line 111, in tmpcb
    callback(*args, **kwargs)
  File &quot;/usr/share/virt-manager/virtManager/libvirtobject.py&quot;, line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File &quot;/usr/share/virt-manager/virtManager/domain.py&quot;, line 1105, in revert_to_snapshot
    self._backend.revertToSnapshot(snap.get_backend())
  File &quot;/usr/lib/python3/dist-packages/libvirt.py&quot;, line 2024, in revertToSnapshot
    if ret == -1: raise libvirtError (&#39;virDomainRevertToSnapshot() failed&#39;, dom=self)
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2019-12-08T08:01:21.847930Z qemu-system-x86_64: Device &#39;drive-virtio-disk0&#39; does not have the requested snapshot &#39;snapshot1&#39;


It only occurs with live-snapshots and with Whonix VMs. 

For me it&#39;s not a big deal, because &quot;normal&quot; snapshots are good enough, I only wanted to say, that this problem seems to exist (reproducible on two machines).</description>
    <language>en</language>
    <lastBuildDate>Mon, 09 Dec 2019 10:11:09 +0000</lastBuildDate>
    <category>KVM</category>
    <atom:link href="http://forums.whonix.org/t/live-snapshots-dont-work/8606.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Live Snapshots don&#39;t work</title>
        <dc:creator><![CDATA[evo]]></dc:creator>
        <description><![CDATA[
            <p>Yes of course, that sounds logical. Thank your for the explanation.</p>
          <p><a href="http://forums.whonix.org/t/live-snapshots-dont-work/8606/3">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/live-snapshots-dont-work/8606/3</link>
        <pubDate>Mon, 09 Dec 2019 10:11:09 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-8606-3</guid>
        <source url="http://forums.whonix.org/t/live-snapshots-dont-work/8606.rss">Live Snapshots don&#39;t work</source>
      </item>
      <item>
        <title>Live Snapshots don&#39;t work</title>
        <dc:creator><![CDATA[HulaHoop]]></dc:creator>
        <description><![CDATA[
            <p>They don’t work when shared folders are attached. That’s because the machine state is not totally self contained for it to be archived.</p>
          <p><a href="http://forums.whonix.org/t/live-snapshots-dont-work/8606/2">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/live-snapshots-dont-work/8606/2</link>
        <pubDate>Sun, 08 Dec 2019 17:05:26 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-8606-2</guid>
        <source url="http://forums.whonix.org/t/live-snapshots-dont-work/8606.rss">Live Snapshots don&#39;t work</source>
      </item>
      <item>
        <title>Live Snapshots don&#39;t work</title>
        <dc:creator><![CDATA[evo]]></dc:creator>
        <description><![CDATA[
            <p>KVM, Whonix-15.0.0.7.1: Live snapshots don’t work</p>
<p>When I want to start a saved live snapshot I always get error messages like this:</p>
<p>internal error: process exited while connecting to monitor: 2019-12-08T08:01:21.847930Z qemu-system-x86_64: Device ‘drive-virtio-disk0’ does not have the requested snapshot ‘snapshot1’</p>
<p>Traceback (most recent call last):<br>
File “/usr/share/virt-manager/virtManager/asyncjob.py”, line 75, in cb_wrapper<br>
callback(asyncjob, *args, **kwargs)<br>
File “/usr/share/virt-manager/virtManager/asyncjob.py”, line 111, in tmpcb<br>
callback(*args, **kwargs)<br>
File “/usr/share/virt-manager/virtManager/libvirtobject.py”, line 66, in newfn<br>
ret = fn(self, *args, **kwargs)<br>
File “/usr/share/virt-manager/virtManager/domain.py”, line 1105, in revert_to_snapshot<br>
self._backend.revertToSnapshot(snap.get_backend())<br>
File “/usr/lib/python3/dist-packages/libvirt.py”, line 2024, in revertToSnapshot<br>
if ret == -1: raise libvirtError (‘virDomainRevertToSnapshot() failed’, dom=self)<br>
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2019-12-08T08:01:21.847930Z qemu-system-x86_64: Device ‘drive-virtio-disk0’ does not have the requested snapshot ‘snapshot1’</p>
<p>It only occurs with live-snapshots and with Whonix VMs.</p>
<p>For me it’s not a big deal, because “normal” snapshots are good enough, I only wanted to say, that this problem seems to exist (reproducible on two machines).</p>
          <p><a href="http://forums.whonix.org/t/live-snapshots-dont-work/8606/1">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/live-snapshots-dont-work/8606/1</link>
        <pubDate>Sun, 08 Dec 2019 15:37:11 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-8606-1</guid>
        <source url="http://forums.whonix.org/t/live-snapshots-dont-work/8606.rss">Live Snapshots don&#39;t work</source>
      </item>
  </channel>
</rss>
